### ISSUE TITLE
Move or get rid of metric_fu requirement on Rakefile line 58?

### ISSUE THREAD

**Issue by agrimm** [michaeledgar/laser#2]
I'd like to build the gem without installing all of the developer dependencies. Does 

```
require 'metric_fu'
```

need to be on line 58?

**Comment by michaeledgar** [comment]
Good call. Probably not right now. Unfortunately, bundler doesn't make it possible to have gems that I want to use for development that aren't in the global gemfile. That's why you'll see "fuubar" is in there too.

I'll trim down some of the stuff I'm not using later today, but I'm not sure getting rid of all the developer dependencies will be possible.
